In [1]:
import csv 
import json
import pandas as pd

In [2]:
with open('data_raw.json') as f:
    data = json.load(f)

In [3]:
# Converting the data into datafrome
df = pd.DataFrame(data)

In [4]:
# Transformation 
# adding inr price also
usd_to_inr = 88.04
df['price_inr'] = (df['price_usd'] * usd_to_inr).round(2)

# Adding tax_inr column also for tax
df['tax_inr'] = (df['price_inr'] * 0.18).round(2) # 18% GST

In [5]:
# Renaming column "Name" to "Item"
df = df.rename(columns={
    'name' : 'item'
})

In [6]:
df_final = df[['id', 'item', 'category', 'price_usd', 'price_inr', 'tax_inr', 'rating']]
df_final

,id,item,category,price_usd,price_inr,tax_inr,rating
0,1,Wireless Mouse,Electronics,25.50,2245.02,404.10,4.5
1,2,Bluetooth Headphones,Audio,55.00,4842.20,871.60,4.3
2,3,Smartwatch,Wearable,120.99,10651.96,1917.35,4.7
3,4,Mechanical Keyboard,Accessories,80.25,7065.21,1271.74,4.6
4,5,USB-C Hub,Accessories,45.75,4027.83,725.01,4.4
5,6,4K Monitor,Electronics,320.00,28172.80,5071.10,4.8
6,7,Gaming Laptop,Computers,1299.99,114451.12,20601.20,4.9
7,8,Portable SSD 1TB,Storage,139.50,12281.58,2210.68,4.7
8,9,Smart Speaker,Audio,89.99,7922.72,1426.09,4.2
9,10,Noise Cancelling Earbuds,Audio,149.00,13117.96,2361.23,4.6
10,11,Action Camera,Photography,210.99,18575.56,3343.60,4.5
11,12,Tripod Stand,Photography,39.99,3520.72,633.73,4.1
12,13,LED Desk Lamp,Home Office,25.99,2288.16,411.87,4.3
13,14,Wireless Charger,Accessories,18.75,1650.75,297.14,4.2
14,15,Smartphone Gimbal,Photography,99.50,8759.98,1576.80,4.4
15,16,Laptop Stand,Home Office,34.50,3037.38,546.73,4.3
16,17,Wireless Router,Networking,89.00,7835.56,1410.40,4.5
17,18,External Hard Drive 2TB,Storage,79.99,7042.32,1267.62,4.6
18,19,Webcam HD 1080p,Electronics,49.99,4401.12,792.20,4.4
19,20,Ergonomic Office Chair,Home Office,229.00,20161.16,3629.01,4.8

In [7]:
# Loading json transformend data into csv file 
df_final.to_csv('products.csv', index=False)
print("✅ Transformation complete → products.csv generated successfully!")
df_final.head()

✅ Transformation complete → products.csv generated successfully!

,id,item,category,price_usd,price_inr,tax_inr,rating
0,1,Wireless Mouse,Electronics,25.50,2245.02,404.10,4.5
1,2,Bluetooth Headphones,Audio,55.00,4842.20,871.60,4.3
2,3,Smartwatch,Wearable,120.99,10651.96,1917.35,4.7
3,4,Mechanical Keyboard,Accessories,80.25,7065.21,1271.74,4.6
4,5,USB-C Hub,Accessories,45.75,4027.83,725.01,4.4